apiVersion: v1
kind: Pod
metadata:
  name: testpd
spec:
  containers:
    - image: kubernetes/pause
      name: testpd
      volumeMounts:
        - mountPath: "/testpd"
          name: "testpd"
  volumes:
    - name: testpd
      gcePersistentDisk:
        # 该GCE PD必须已经存在
        pdName: test
        fsType: ext4
